// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4me5aqlC6jvzoZoQjIpyZu6P_YEITWdw',
    appId: '1:138146009176:web:442808c882fd32de0eba2d',
    messagingSenderId: '138146009176',
    projectId: 'messaging-app-c1bed',
    authDomain: 'messaging-app-c1bed.firebaseapp.com',
    storageBucket: 'messaging-app-c1bed.firebasestorage.app',
    measurementId: 'G-YJM11VPSPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAntfr_WBFBXnI71LGQosjnixayYve8J5A',
    appId: '1:138146009176:android:1945a10b932c00310eba2d',
    messagingSenderId: '138146009176',
    projectId: 'messaging-app-c1bed',
    storageBucket: 'messaging-app-c1bed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaSlXlLpchBT2ZkG6pZSmCypweNHd_KtI',
    appId: '1:138146009176:ios:0f18a5f0e37646f40eba2d',
    messagingSenderId: '138146009176',
    projectId: 'messaging-app-c1bed',
    storageBucket: 'messaging-app-c1bed.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaSlXlLpchBT2ZkG6pZSmCypweNHd_KtI',
    appId: '1:138146009176:ios:0f18a5f0e37646f40eba2d',
    messagingSenderId: '138146009176',
    projectId: 'messaging-app-c1bed',
    storageBucket: 'messaging-app-c1bed.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4me5aqlC6jvzoZoQjIpyZu6P_YEITWdw',
    appId: '1:138146009176:web:f2371b90999286b40eba2d',
    messagingSenderId: '138146009176',
    projectId: 'messaging-app-c1bed',
    authDomain: 'messaging-app-c1bed.firebaseapp.com',
    storageBucket: 'messaging-app-c1bed.firebasestorage.app',
    measurementId: 'G-FWTP7EPZ3F',
  );
}
